---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: devopsdb

spec:
  replicas: 2
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: cont-1
          image: srujan28/k8sdockerweb:db-image
          ports:
            - containerPort: 3306
      imagePullSecrets:
        - name: flmdocker


---
apiVersion: v1
kind: Service
metadata:
  name: dockerwebdb

spec:
  clusterIp: None
  selector:
    app: db
  ports:
    - port: 3306
      targetPort: 3306
